Feature/slice detailand save article screen
capstone-kelompok-7/mobile-disappear pull request #12
Opened 2023-11-13 11:57 UTC by TBPriangga

![DetailArticleScreenAndSaveArtivleScreen](https://github.com/capstone-kelompok-7/mobile-disappear/assets/87335431/671ceb0b-daee-4a0b-9b02-1b3a0c9cbb9f)
1. Menambahkan route di main.dart
2. Membuat halaman Detail article screen
3. Membuat halaman Save article screen

2023-11-13 14:15 UTC, ademrizki requested changes
Nama kelas beda (contoh)

2023-11-14 01:12 UTC, novilfahlevy approved these changes

2023-11-14 04:09 UTC, TBPriangga commented on lib/screens/detail_article_screen.dart
> +                  ),
Oiyaa.. sebenernya bisa sih itu gadipakein row, dibagian Column yang diatas ditambahin Crostart, diganti dulu ya ini?
![SS1](https://github.com/capstone-kelompok-7/mobile-disappear/assets/87335431/1efd2ee8-fcbe-47cb-a5be-9bea76c615de)

2023-11-14 04:40 UTC, novilfahlevy commented on lib/screens/detail_article_screen.dart
> +                  ),
Iya coba ganti dlu aja

2023-11-14 04:50 UTC, TBPriangga commented on lib/screens/detail_article_screen.dart
> +                  ),
ok sudah

2023-11-14 11:43 UTC, iqbalgany approved these changes

2023-11-14 11:53 UTC, merged